### PR TITLE
Correct orientation realignement

### PR DESCRIPTION
**Pull request by kingjr**
@chri4354 I just understood what we did wrong yesterday: we just forgot to take the absolute (or square) error before averaging across trials:
```
angle_errors = (predict_angles - true_angles + pi) % (2 * pi) - pi
plt.matshow(np.mean(angle_errors ** 2, axis=2), origin='lower')
```
I made you a toy example to break the logic down step by step. It's also a good start if you want to compare SVR, SVC, circle versus 'pythagore' regression, utility of +7.5 degrees etc.

### CODE REVIEW

**Comment by kingjr** [comment]
You have to accept the pull request, and then pull the github rep back onto your local machine before you make any new modifications

```
git checkout master
git pull http://github.com/chri/Paris_orient-deco master
```

**Comment by chri4354** [comment]
I have an horrible connection so I cannot pull the new code onto local machine. Is it ok if I just copy and paste the toy example? Or did you change other files?

**Comment by kingjr** [comment]
I didn't change any other files, but if you modify independently of the
pull, you're going to make a git conflict. Plus pulling the git should be
similar to sending a text email.

Do you have a "freewifi" around you? I can give you my codes

**Comment by chri4354** [comment]
no unfortunately not. I suspect there is a protocol issue. I have problems also in sending emails

**Comment by kingjr** [comment]
Ok,

before making modifications  go in the terminal
cd your/path/to/the/git/folder
git branch from_monday
git checkout from_monday

and then continue working;)

**Comment by chri4354** [comment]
Just to make sure are the commands to be executed just:
git checkout master
and
git pull http://github.com/chri4354/Paris_orientation-decoding.git master?

**Comment by kingjr** [comment]
I don't think you need to specify 'master' when pulling but yes. Don't
spend too much time on this, if there's a conflict we'll find a solution

**Pull request merged**
